# fly.toml app configuration file generated for bohio-server on 2025-03-12T13:40:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bohio-server'
primary_region = 'mia'

[build]

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  FRONTEND_URL = 'https://www.bohio.net'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
