name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.4' # Use the version you need

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build --configuration Release

      # Step 5: Run integration tests
      - name: Run integration tests
        run: dotnet test Homespirations.Api.IntegrationTests/Homespirations.Api.IntegrationTests.csproj --configuration Release

      # Step 6: Publish the app
      - name: Publish the app
        run: dotnet publish Homespirations.Api/Homespirations.Api.csproj --configuration Release --output ./publish --runtime linux-x64 --self-contained false

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure deployment only happens if the build succeeds
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
